// <auto-generated />
namespace EFDDD.DataModel.Migrations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddMigrationInitialSchema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMigrationInitialSchema));
        
        string IMigrationMetadata.Id
        {
            get { return "201507111116007_Add-Migration InitialSchema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
